### ISSUE TITLE
Evaluation method on cities_dataset 

### ISSUE THREAD

**Issue by SoulHomes** [ennauata/buildings2vec#2]
Hi, could you give instructions on how to evaluate the model with the edge metrics on cities_dataset ? Thanks.

**Comment by ennauata** [comment]
Hi, for computing the metrics on cities_dataset you should use the class Metrics defined [here](https://github.com/ennauata/buildings2vec/blob/c4cc103aec1aece08c86dfd945753405abb1ad3d/IP/utils/metrics.py#L9). Also, [here](https://github.com/ennauata/buildings2vec/blob/c4cc103aec1aece08c86dfd945753405abb1ad3d/IP/experiments/.ipynb_checkpoints/exp_0-checkpoint.py#L26) is an example on how to use the class.

**Comment by SoulHomes** [comment]
Thank you very much ：）
