### ISSUE TITLE
gurobi licence dependency 

### ISSUE THREAD

**Issue by mkulaczkowski** [ennauata/buildings2vec#4]
I would like to thank you for very impressive paper and code - however, I was unable to run the final step due to the following error: gurobipy.GurobiError: Model too large for size-limited license

Is the full gurobipy licence required to run this code or I did something wrong?
Thanks.

**Comment by ennauata** [comment]
Hello @mkulaczkowski, thanks for the interest in our work!  Indeed, we had to use the full gurobipy license for this implementation. If I am not wrong, it's free for academia purpose [[here]](https://www.gurobi.com/downloads/end-user-license-agreement-academic/).
